### PR TITLE
Don't depend on distribute which doesn't work on Python 3.6

### PR DESCRIPTION
**Pull request by lalinsky**
Having the dependency on distribute makes it impossible to install the library on Python 3.6, it fails with an error like this:

```
Collecting distribute (from pyzmail==1.0.3)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xtpcx21q/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-build-xtpcx21q/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-build-xtpcx21q/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/tmp/pip-build-xtpcx21q/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/pip-build-xtpcx21q/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/pip-build-xtpcx21q/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

As far as I can see, it works fine even without distribute.

### CODE REVIEW

**Comment by c-w** [comment]
See also https://github.com/aspineux/pyzmail/issues/15#issuecomment-289242646 for a Python 3.6 compatible fork and PyPI release.
